name: C3 Pipeline
on: [push]
jobs:
  noble:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/dairlab/docker-dair/noble-dair-base:v1.42
      credentials:
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
      options: --cpus 4
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Checking code formatting ...
      - run: apt update && apt install -y clang-format
      - run: ./tools/scripts/check_format.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."
